password: {"program1":"Haxor","program2":"RoXor"} # Hash where keys are program names, and values associated passwords
database:
  adapter: 'mysql2' # or 'postgresql' or 'sqlite3'
  host: 'localhost'
  database: 'your_database'
  username: 'your_username'
  password: 'your_password'
